# VARIABLES FOR LOAD ONTOLOGY
#jsonpath = ./json/manzoni.json
#conn_str = jdbc:virtuoso://dante1.isti.cnr.it:1111/charset=UTF-8/log_enable=2
conn_str = jdbc:virtuoso://localhost:1111/charset=UTF-8/log_enable=2
imported_ontologies = ./Triplify/modelDoc/imported-ontologies.owl
imported_ontologies2 = 

ontology1 = ./Triplify/modelDoc/ontology.owl
ontology2 = ./Triplify/modelDoc/narrazioni.ttl

folderOntologies = ./Triplify/modelDoc/
#/home/filippo/workspace/NarraTripleOWLApi/modelDoc/swrl.owl

#add New Axiom And Entity only if expanseOntology is true
expanseOntology = true
doReasoning = false

#VARIALBLES FOR REASONING OPTION infer matching axioms to a variable only if that value is yes
InferClassAssertionAxiom = no
#InferClassAssertionAxiom = yes
InferSubClassAxiom = no
InferEquivalentClassAxiom = no
InferDisjointClassesAxiom = no
InferPropertyAssertion = no
InferInverseObjectPropertiesAxiom = no
InferEquivalentObjectPropertyAxiom = no
InferSubObjectPropertyAxiom = no
#InferInverseObjectPropertiesAxiom = yes
#InferEquivalentObjectPropertyAxiom = yes
#InferSubObjectPropertyAxiom = yes
InferEquivalentDataPropertiesAxiom = no
InferSubDataPropertyAxiom = no
#InferEquivalentDataPropertiesAxiom = yes
#InferSubDataPropertyAxiom = yes
InferObjectPropertyCharacteristicAxiom = no
InferDataPropertyCharacteristicAxiom = no

# VARIABLES FOR SERVER LOG-IN AND STORING

baseURI=  http://localhost/reasonedOntology/NewOnto
#http://dantesources.org/narratives (non funzionante)

# VARIABLES FOR STORE
#owl_path= ./Target/n.owl
ontoUtility_path= ./owl/narrazioni.owl
trigFile_path = ./owl/narrazioni.trig
reportFile= ./Triplify/report.txt
classTreesReportFile = ./Triplify/classTrees.txt

#swrl_rules = ./modelDoc/imported-ontologies.owl
#importedOntologies = ./Target/n.owl
